version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.20.0

jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install pnpm
          command: npm install -g pnpm

      # dependencies
      # we do not use caches here because monorepos have their own package.json files
      # it is fast to install dependencies on CI
      - run:
          name: Install dependencies
          command: pnpm install

      # tests
      - run:
          name: Run tests
          command: pnpm run test

      # TODO: type check

      # TODO: build