version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.20.0

jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install pnpm
          command: npm install -g pnpm

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: pnpm install

      - run:
          name: Run tests
          command: pnpm run test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .