name: 🩺 CI Lint

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

permissions:
    contents: read

jobs:
    eslint:
        runs-on: ubuntu-latest

        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🌡️ Run ESLint
              run: pnpm run lint

    typecheck:
        runs-on: ubuntu-latest

        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🧼 Type checking
              run: npm run lint:types
