name: 📦 CI Preview

on:
    pull_request:
        branches: [main, dev]

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest

        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: 📦 Build
              run: pnpm run build

            - name: 📦 Build demo
              run: pnpm run build:demo

            - name: 🚀 Deploy to Vercel (demo)
              uses: amondnet/vercel-action@v25
              id: vercel-demo
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID}}

            - name: 🚀 Deploy to Vercel (storybook)
              uses: amondnet/vercel-action@v25
              id: vercel-storybook
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID_STORYBOOK}}

            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ success() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      CI Pipeline: Success 🏆
                      **[View Deployment]**
                      - [Doc](${{ steps.vercel-demo.outputs.preview-url }}/doc/)
                      - [Sheet](${{ steps.vercel-demo.outputs.preview-url }}/sheet/)
                      - [Slide](${{ steps.vercel-demo.outputs.preview-url }}/slide/)

                      **[View Storybook]**
                      - [Storybook](${{ steps.vercel-storybook.outputs.preview-url }}/)
                  nofail: false
                  nodetail: false
                  color: 0x00b894
                  username: GitHub Actions

            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ failure() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      CI Pipeline: Unsuccessful 📛
                      **[View PR]**
                      [click here](${{ github.event.pull_request.html_url }})
                  nofail: false
                  nodetail: false
                  color: 0xd63031
                  username: GitHub Actions

            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              id: fc
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ## View Deployment
                      | 📝 Doc | 📊 Sheet | 📽️ Slide |
                      | --- | --- | --- |
                      | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/doc/) | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/sheet/) | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/slide/) |

                      ## View Storybook
                      | 📚 Storybook |
                      | --- |
                      | [🔗 Preview link](${{ steps.vercel-storybook.outputs.preview-url }}/) |
                  edit-mode: replace
