name: 📤 Preview Deploy

on:
    workflow_run:
        workflows: ['📦 Preview Build']
        types: [completed]

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            # Get PR ID from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-id

            - name: get PR id
              id: pr
              run: echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

            # Get PR ID from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-ref

            - name: get PR ref
              id: ref
              run: echo "ref=$(<pr-ref.txt)" >> $GITHUB_OUTPUT

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ steps.ref.outputs.ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            #  ================= Deploy Demo =================
            - name: 📦 Build demo
              run: pnpm run build:demo

            - name: Copy demo to workspace
              run: |
                  mkdir .workspace
                  cp -r ./examples/univer-doc-ts/local .workspace/doc
                  cp -r ./examples/univer-sheet-ts/local .workspace/sheet

            - name: 🚀 Deploy to Vercel (demo)
              uses: amondnet/vercel-action@v25
              id: vercel-demo
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID}}

            # ================= Deploy Storybook =================
            - name: 📦 Build storybook
              run: pnpm run build:storybook

            - name: 🚀 Deploy to Vercel (storybook)
              uses: amondnet/vercel-action@v25
              id: vercel-storybook
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID_STORYBOOK}}

            # ================= Notify Discord =================
            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ success() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      CI Pipeline: Success 🏆
                      **[View Deployment]**
                      - [Doc](${{ steps.vercel-demo.outputs.preview-url }}/doc/)
                      - [Sheet](${{ steps.vercel-demo.outputs.preview-url }}/sheet/)
                      - [Slide](${{ steps.vercel-demo.outputs.preview-url }}/slide/)

                      **[View Storybook]**
                      - [Storybook](${{ steps.vercel-storybook.outputs.preview-url }}/)
                  nofail: false
                  nodetail: false
                  color: 0x00b894
                  username: GitHub Actions

            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ failure() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      CI Pipeline: Unsuccessful 📛
                      **[PR ID]**
                      #${{ steps.pr.outputs.id }}
                  nofail: false
                  nodetail: false
                  color: 0xd63031
                  username: GitHub Actions

            # ================= Create Comment =================
            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              id: fc
              with:
                  issue-number: ${{ steps.pr.outputs.id }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ steps.pr.outputs.id }}
                  body: |
                      ## View Deployment
                      | 📝 Doc | 📊 Sheet | 📽️ Slide |
                      | --- | --- | --- |
                      | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/doc/) | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/sheet/) | [🔗 Preview link](${{ steps.vercel-demo.outputs.preview-url }}/slide/) |

                      ## View Storybook
                      | 📚 Storybook |
                      | --- |
                      | [🔗 Preview link](${{ steps.vercel-storybook.outputs.preview-url }}/) |
                  edit-mode: replace
