name: 📤 Preview Deploy

on:
    workflow_run:
        workflows: ['📦 Build']
        types: [completed]

permissions:
    contents: read
    pull-requests: write

jobs:
    setup:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        outputs:
            id: ${{ steps.pr.outputs.id }}
            ref: ${{ steps.ref.outputs.ref }}

        steps:
            # Get PR ID from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-id

            - name: get PR id
              id: pr
              run: echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

            # Get PR ID from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-ref

            - name: get PR ref
              id: ref
              run: echo "ref=$(<pr-ref.txt)" >> $GITHUB_OUTPUT

    prepare:
        runs-on: ubuntu-latest
        needs: [setup]

        steps:
            # ================= Create Comment =================
            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              if: ${{ needs.setup.outputs.id != '' }}
              id: fc
              with:
                  issue-number: ${{ needs.setup.outputs.id }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              if: ${{ needs.setup.outputs.id != '' }}
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ needs.setup.outputs.id }}
                  body: |
                      ## View Deployment

                      🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧
                      Still cooking, please come back later
                      🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧
                  edit-mode: replace


    build-demo:
        runs-on: ubuntu-latest
        needs: [setup]

        outputs:
            preview-url: ${{ steps.vercel-demo.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ needs.setup.outputs.ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            #  ================= Deploy Demo =================
            - name: 📦 Build demo
              run: pnpm run build:demo

            - name: Copy demo to workspace
              run: |
                  mkdir .workspace
                  cp -r ./examples/univer-doc-ts/local .workspace/doc
                  cp -r ./examples/univer-sheet-ts/local .workspace/sheet

            - name: 🚀 Deploy to Vercel (demo)
              uses: amondnet/vercel-action@v25
              id: vercel-demo
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID}}

    build-storybook:
        runs-on: ubuntu-latest
        needs: [setup]

        outputs:
            preview-url: ${{ steps.vercel-storybook.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ needs.setup.outputs.ref }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install

            # ================= Deploy Storybook =================
            - name: 📦 Build storybook
              run: pnpm run build:storybook

            - name: 🚀 Deploy to Vercel (storybook)
              uses: amondnet/vercel-action@v25
              id: vercel-storybook
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID_STORYBOOK}}

    notify:
        runs-on: ubuntu-latest
        needs: [setup, build-demo, build-storybook]

        steps:
            # ================= Notify Discord =================
            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ success() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      Ref: ${{ needs.setup.outputs.ref }}

                      🏆 CI Pipeline: Success
                      **[View Deployment]**
                      - [Doc](${{ needs.build-demo.outputs.preview-url }}/doc/)
                      - [Sheet](${{ needs.build-demo.outputs.preview-url }}/sheet/)
                      - [Slide](${{ needs.build-demo.outputs.preview-url }}/slide/)

                      **[View Storybook]**
                      - [Storybook](${{ needs.build-storybook.outputs.preview-url }}/)
                  nofail: false
                  nodetail: false
                  nocontext: false
                  noprefix: true
                  color: 0x00b894
                  username: GitHub Actions

            - name: 👾 Discord Notification
              uses: sarisia/actions-status-discord@v1
              if: ${{ failure() }}
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  description: |
                      Ref: ${{ needs.setup.outputs.ref }}

                      📛 CI Pipeline: Unsuccessful
                      **[PR ID]**
                      #${{ needs.setup.outputs.id }}
                  nofail: false
                  nodetail: false
                  nocontext: false
                  noprefix: true
                  color: 0xd63031
                  username: GitHub Actions

            # ================= Create Comment =================
            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              if: ${{ needs.setup.outputs.id != '' }}
              id: fc
              with:
                  issue-number: ${{ needs.setup.outputs.id }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              if: ${{ needs.setup.outputs.id != '' }}
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ needs.setup.outputs.id }}
                  body: |
                      ## View Deployment
                      | 📝 Doc | 📊 Sheet | 📽️ Slide |
                      | --- | --- | --- |
                      | [🔗 Preview link](${{ needs.build-demo.outputs.preview-url }}/doc/) | [🔗 Preview link](${{ needs.build-demo.outputs.preview-url }}/sheet/) | [🔗 Preview link](${{ needs.build-demo.outputs.preview-url }}/slide/) |

                      ## View Storybook
                      | 📚 Storybook |
                      | --- |
                      | [🔗 Preview link](${{ needs.build-storybook.outputs.preview-url }}/) |
                  edit-mode: replace
