name: 🥷 Release Nightly

on:
    workflow_dispatch:
    schedule:
        - cron: '0 16 * * *'

permissions:
    contents: read

jobs:
    release-nightly:
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest

        outputs:
            version: ${{ steps.nightly-version.outputs.version }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: ${{ secrets.VERDACCIO_URL }}

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: 📌 Get package version (version + date)
              id: nightly-version
              run: |
                  original_version=$(node -p "require('./package.json').version")
                  version_number=$(echo "$original_version" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
                  echo "version=$version_number-nightly.$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

            - name: 🔏 Set all monorepo's package version
              run: |
                  for package in $(ls packages); do
                      node -e "const fs = require('fs'); const package = JSON.parse(fs.readFileSync('./packages/$package/package.json')); package.version = '${{ steps.nightly-version.outputs.version }}'; fs.writeFileSync('./packages/$package/package.json', JSON.stringify(package, null, 4));"
                  done

            - name: 🚚 Install dependencies
              run: pnpm install

            - name: 📦 Build
              run: pnpm run build

            - name: 🐙 Publish
              run: pnpm publish --access public --tag nightly -r
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

    build-demo:
        runs-on: ubuntu-latest
        needs: [release-nightly]

        outputs:
            preview-url: ${{ steps.vercel-demo.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            #  ================= Deploy Demo =================
            - name: 📦 Build demo
              run: pnpm run build:demo

            - name: Copy demo to workspace
              run: |
                  mkdir .workspace
                  cp -r ./examples/local/* .workspace

            - name: 🚀 Deploy to Vercel (demo)
              uses: amondnet/vercel-action@v25
              id: vercel-demo
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID}}
                  vercel-project-id: ${{ secrets.PROJECT_ID}}

    build-storybook:
        runs-on: ubuntu-latest
        needs: [release-nightly]

        outputs:
            preview-url: ${{ steps.vercel-storybook.outputs.preview-url }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            # ================= Deploy Storybook =================
            - name: 📦 Build storybook
              run: pnpm run build:storybook

            - name: 🚀 Deploy to Vercel (storybook)
              uses: amondnet/vercel-action@v25
              id: vercel-storybook
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.ORG_ID }}
                  vercel-project-id: ${{ secrets.PROJECT_ID_STORYBOOK }}

    notify:
        needs: [release-nightly, build-demo, build-storybook]
        runs-on: ubuntu-latest

        steps:
            - name: Invoke deployment hook
              uses: distributhor/workflow-webhook@v3
              with:
                  webhook_url: ${{ secrets.WEBHOOK_URL }}
                  data: >
                      {
                          "type": "release",
                          "version": "${{ github.ref_name }}",
                          "workflow": {
                              "id": "${{ github.run_id }}"
                          },
                          "preview": {
                              "📑 Examples": "${{ needs.build-demo.outputs.preview-url }}/",
                              "📚 Storybook": "${{ needs.build-storybook.outputs.preview-url }}/"
                          }
                      }
